{% set name = "debtcollector" %}
{% set version = "2.4.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "1bc03e2d9017de480c41cf3e5a0d8cc95f1b0c8f1339281b4eca8a22acf76a23" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.7
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >=3.7
    - pbr !=2.1.0,>=2.0.0
    - wrapt >=1.7.0
    - importlib_metadata
test:
  imports:
    - debtcollector
    - debtcollector.moves
    - debtcollector.renames
    - debtcollector.removals
    - debtcollector.fixtures
  requires:
    - pip
  commands:
    - pip check

about:
  home: http://docs.openstack.org/developer/debtcollector/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.
  dev_url: https://git.openstack.org/cgit/openstack/debtcollector
  doc_url: http://docs.openstack.org/developer/debtcollector/

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
