{% set name = "debtcollector" %}
{% set version = "3.0.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "2a8917d25b0e1f1d0d365d3c1c6ecfc7a522b1e9716e8a1a4a915126f7ccea6f" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  noarch: python
  number: 1
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
    - pbr !=2.1.0,>=2.0.0

  run:
    - python >={{ python_min }}
    - wrapt >=1.7.0
test:
  imports:
    - debtcollector
    - debtcollector.moves
    - debtcollector.renames
    - debtcollector.removals
    - debtcollector.fixtures
  requires:
    - pip
    - python {{ python_min }}
  commands:
    - pip check

about:
  home: http://docs.openstack.org/developer/debtcollector/
  license_file: LICENSE
  license: Apache-2.0
  license_family: Apache
  summary: A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.
  dev_url: https://git.openstack.org/cgit/openstack/debtcollector
  doc_url: http://docs.openstack.org/developer/debtcollector/

extra:
  recipe-maintainers:
    - anguslees
    - tschoonj
