{% set name = "debtcollector" %}
{% set version = "2.1.0" %}
{% set bundle = "tar.gz" %}
{% set hash = "a25fc6215560d81cb9f2a0b58d6c834f2a24010987027bde169599e138a205af" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  sha256: {{ hash }}

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv


requirements:
  build:
    - python
    - pip
    - pbr !=2.1.0,>=2.0.0

  run:
    - python
    - pbr !=2.1.0,>=2.0.0
    - six >=1.10.0
    - wrapt >=1.7.0
    - funcsigs >=1.0.0  # [py26 or py27]

test:
  imports:
    - debtcollector
    - debtcollector.moves
    - debtcollector.renames
    - debtcollector.removals
    - debtcollector.fixtures

about:
  home: http://docs.openstack.org/developer/debtcollector/
  license_file: LICENSE
  license: Apache 2.0
  license_family: Apache
  summary: A collection of Python deprecation patterns and strategies that help you collect your technical debt in a non-destructive manner.
  dev_url: https://git.openstack.org/cgit/openstack/debtcollector
  doc_url: http://docs.openstack.org/developer/debtcollector/

extra:
  recipe-maintainers:
    - anguslees
    - pmlandwehr
