travis:
  secure:
    BINSTAR_TOKEN: JG0iKSzGhktwyHzPXgEGupmhpFqv2WsbCx31URqw8oedCwNP71M4qI+SGA3+FPFVMAAQobBQR/aFVeMoNuw9AE15OwZ9Lte40X2MDw6qjwaJiYOETqavgZ72ZK9sCyKvNMVA/7jhlrEMDnLIMNyZ+/h1yhcJLt4u6C3UDnI4qL9FzZ+AMOJZ+nYMMECpab6GqCO3KSveVfC2CTVX1MMdr1X7FxNNh3vZO4PVtQE4Dcp3Siz765BpRPlUYDDLBj2k2Ifd01Lt9SHf9E+ceL4w2VudXaVDOPWmIIxeUL9IL6Dd+7LADNzKbY6ICK4dhlc7twUFMUfcegA/+rct27oycY3NsJtu83F9aMgu1Q9lm+wQipNLG4WtkYj4mloq+ieyfXfKwtRYdxcPdkR7/HNSn2jwi5gSfG0vSvlQba5BYzusuQpcALA2Os6aaoM+WojB+k5NaHuUhpxyQNASDCoJT0i7KmkjKKWJjn0rcTtb4huMXxe1tV+3V0NV1UcHtxW0bUlBMPN4rNAz7XkuMEjzUghpD/MDTq9I6R887gsPzh9sQeT+gMlVpFS2rlv3LCalV0XYzKPISGalWliRDS2keM5BIpURsuidlBf7LauvGD7PA3D8ZrBS08V2us6Hk9pLey+vAFUkkye6yTAWMm/xMEjvMtGqBq3+6iu5xR2rQdE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
